# Generated by Django 5.2.4 on 2025-08-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apostilas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
    ]
